edit_mode = "vim"
path = ["C:\\Users\\jonst\\.bin"]
prompt = "echo $(starship prompt)"
startup = ["alias l [x] { ls $x } -s"]
table_mode = "light"
use_starship = true

[line_editor]
completion_match_method = "case-insensitive"
