edit_mode = "vim"
path = ["/home/linuxbrew/.linuxbrew/bin", "/home/linuxbrew/.linuxbrew/sbin", "/home/jon/.volta/bin", "/Users/jon/.cargo/bin", "/usr/local/sbin", "/usr/local/bin", "/usr/sbin", "/usr/bin", "/sbin", "/bin", "/usr/games", "/usr/local/games", "/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin", "/mnt/c/Program Files/Microsoft MPI/Bin/", "/mnt/c/WINDOWS/system32", "/mnt/c/WINDOWS", "/mnt/c/WINDOWS/System32/Wbem", "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/", "/mnt/c/Program Files/dotnet/", "/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/", "/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/", "/mnt/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn/", "/mnt/c/Program Files/Microsoft SQL Server/140/Tools/Binn/", "/mnt/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn/", "/mnt/c/Program Files/Microsoft SQL Server/140/DTS/Binn/", "/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn/", "/mnt/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn/", "/mnt/c/Program Files/nodejs", "/mnt/c/Program Files/Docker/Docker/resources/bin", "/mnt/c/ProgramData/DockerDesktop/version-bin", "/mnt/c/Users/jonst/scoop/shims", "/mnt/c/Users/jonst/AppData/Local/Microsoft/WindowsApps", "/mnt/c/Users/jonst/.dotnet/tools", "/mnt/c/Users/jonst/AppData/Local/Programs/Fiddler", "/mnt/c/Users/jonst/AppData/Local/MaxTo/", "/mnt/c/Users/jonst/AppData/Local/Programs/Microsoft VS Code/bin"]
prompt = "echo $(starship prompt)"
startup = ["alias l [x] { ls $x } -s"]
table_mode = "light"

[env]
CARGO_TARGET_DIR = "/Users/jon/.cargo/target"
EDITOR = "vim"
HOMEBREW_CELLAR = "/home/linuxbrew/.linuxbrew/Cellar"
HOMEBREW_PREFIX = "/home/linuxbrew/.linuxbrew"
HOMEBREW_REPOSITORY = "/home/linuxbrew/.linuxbrew/Homebrew"
INFOPATH = "/home/linuxbrew/.linuxbrew/share/info"
LC_ALL = "en_US.UTF-8"
MANPATH = "/home/linuxbrew/.linuxbrew/share/man"
VOLTA_HOME = "/home/jon/.volta"

[line_editor]
completion_match_method = "case-insensitive"
